In [6]:
#import libraries
#!pip install kaggle
!pip install kaggle

Requirement already satisfied: kaggle in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (1.8.3)

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: black>=24.10.0 in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (26.1.0)
Requirement already satisfied: bleach in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (6.2.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (0.1.15)
Requirement already satisfied: mypy>=1.15.0 in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (1.19.1)
Requirement already satisfied: packaging in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (24.2)
Requirement already satisfied: protobuf in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (6.33.5)
Requirement already satisfied: python-dateutil in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (2.32.3)
Requirement already satisfied: six>=1.10 in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: tqdm in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (4.67.1)
Requirement already satisfied: types-requests in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (2.32.4.20260107)
Requirement already satisfied: types-tqdm in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (4.67.0.20250809)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (2.2.3)
Requirement already satisfied: click>=8.0.0 in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from black>=24.10.0->kaggle) (8.3.1)
Requirement already satisfied: mypy-extensions>=0.4.3 in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from black>=24.10.0->kaggle) (1.1.0)
Requirement already satisfied: pathspec>=1.0.0 in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from black>=24.10.0->kaggle) (1.0.4)
Requirement already satisfied: platformdirs>=2 in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from black>=24.10.0->kaggle) (4.3.6)
Requirement already satisfied: pytokens>=0.3.0 in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from black>=24.10.0->kaggle) (0.4.1)
Requirement already satisfied: typing_extensions>=4.6.0 in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from mypy>=1.15.0->kaggle) (4.15.0)
Requirement already satisfied: librt>=0.6.2 in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from mypy>=1.15.0->kaggle) (0.7.8)
Requirement already satisfied: webencodings in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from requests->kaggle) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from requests->kaggle) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from requests->kaggle) (2024.8.30)
Requirement already satisfied: colorama in c:\users\prakh\appdata\local\programs\python\python313\lib\site-packages (from tqdm->kaggle) (0.4.6)

In [7]:
import kaggle

In [13]:
!kaggle datasets download -d prakharkandpal/retail-orders -f orders.csv --force

Dataset URL: https://www.kaggle.com/datasets/prakharkandpal/retail-orders
License(s): Community Data License Agreement - Permissive - Version 1.0
Downloading orders.csv to C:\Users\prakh

  0%|          | 0.00/1.29M [00:00<?, ?B/s]
 78%|#######7  | 1.00M/1.29M [00:02<00:00, 505kB/s]
100%|##########| 1.29M/1.29M [00:02<00:00, 664kB/s]
100%|##########| 1.29M/1.29M [00:02<00:00, 618kB/s]

In [19]:
#Extract file from zip file
import zipfile

zip_ref = zipfile.ZipFile(r"C:\Users\prakh\Downloads\orders.csv.zip")
zip_ref.extractall("C:/Users/prakh/Downloads")  # extracts into Downloads folder
zip_ref.close()

In [25]:
#read data from the file and handle null values
import pandas as pd
df= pd.read_csv('orders.csv',na_values=['Not Available','unknown'])
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [26]:
df

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [33]:
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'cost_price', 'list_price', 'quantity',
       'discount_percent'],
      dtype='object')

In [34]:
#rename columns names ..make them lower case and replace space with underscore
df.columns=df.columns.str.lower()

In [32]:
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'cost_price', 'list_price', 'quantity',
       'discount_percent'],
      dtype='object')

In [31]:
df.columns=df.columns.str.replace(' ','_')

In [36]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [39]:
#derive new columns discount , sale price and profit
df['discount']=df['list_price']*df['discount_percent']*.01

In [42]:
df['sale_price']=df['list_price']-df['discount']

In [43]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8

In [45]:
df['Profit']=df['sale_price']-df['cost_price']
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,Profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [46]:
#convert order date from object data type to datetime
df['order_date']=pd.to_datetime(df['order_date'],format="%Y-%m-%d")

In [48]:
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
Profit                     float64
dtype: object

In [49]:
#drop cost price list price and discount percent columns
df.drop(columns=['list_price','cost_price','discount_percent'],inplace=True)

In [50]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,Profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [54]:
!pip install pyodbc

Collecting pyodbc
  Downloading pyodbc-5.3.0-cp313-cp313-win_amd64.whl.metadata (2.8 kB)
Downloading pyodbc-5.3.0-cp313-cp313-win_amd64.whl (70 kB)
Installing collected packages: pyodbc
Successfully installed pyodbc-5.3.0

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [80]:
import sqlalchemy as sal
engine = sal.create_engine(
    "mssql+pyodbc://MSI/master?driver=ODBC+Driver+17+for+SQL+Server"
)
conn = engine.connect()

In [75]:
from sqlalchemy import create_engine

engine = create_engine("mssql+pyodbc://MSI/master?driver=ODBC+Driver+17+for+SQL+Server")  # or your DB URL
conn = engine.connect()

In [81]:
df.to_sql('df_orders', con=conn, index=False, if_exists='append')

38

In [82]:
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'quantity', 'discount', 'sale_price', 'Profit'],
      dtype='object')